apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: default
data:
  logstash.yml: |
    http.host: 0.0.0.0
    log.level: debug
    node.name: logstash

  logstash.conf: |
    input {
     tcp{
      port => 5000
      codec => json
      }
    }
    
    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        index => "spring-%{app}"
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: logstash

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.15.0
          securityContext:
            readOnlyRootFilesystem: false
          imagePullPolicy: "IfNotPresent"
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: LS_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          ports:
            - containerPort: 5000
              name: logstash
            - containerPort: 5044
            - containerPort: 9600
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf

      volumes:
        - name: pipeline
          configMap:
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
