apiVersion: v1
kind: Service
metadata:
  name: main
spec:
  selector:
    app: main
  ports:
    - protocol: TCP
      name: main
      port: 5001
      targetPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  labels:
    app: main
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: borntonight/main:1
          ports:
            - containerPort: 5001
          env:
            - name: SPRING_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_USER
            - name: SPRING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_PASSWORD
            - name: SPRING_ADMIN_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_HOST
            - name: SPRING_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_USER
            - name: SPRING_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: REDIS_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_KEY
            - name: ACCESS_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: ACCESS_TOKEN_EXPIRATION
            - name: REFRESH_TOKEN_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: REFRESH_TOKEN_EXPIRATION
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: KAFKA_HOST
            - name: KAFKA_TOPIC
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: KAFKA_TOPIC
            - name: KAFKA_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: KAFKA_CLIENT_ID
            - name: GRPC_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: GRPC_HOST
            - name: LOGSTASH_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: LOGSTASH_HOST

