apiVersion: v1
kind: Service
metadata:
  name: reader
spec:
  selector:
    app: reader
  ports:
    - protocol: TCP
      name: reader
      port: 5002
      targetPort: 5002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
  labels:
    app: reader
spec:
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
        - name: reader
          image: borntonight/reader:1
#          ports:
#            - containerPort: 5002
          env:
            - name: SPRING_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_USER
            - name: SPRING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_PASSWORD
            - name: SPRING_ADMIN_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_HOST
            - name: SPRING_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_USER
            - name: SPRING_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SPRING_ADMIN_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
            - name: GRPC_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: GRPC_HOST
            - name: LOGSTASH_HOST
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: LOGSTASH_HOST

