apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-claim0
  labels:
    type: local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/redis"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim0
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7.4-rc-alpine
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: REDIS_PASSWORD
          volumeMounts:
            - name: redis-claim0
              mountPath: /redis
      volumes:
        - name: redis-claim0
          persistentVolumeClaim:
            claimName: redis-claim0